# Generated by Django 4.0.1 on 2022-02-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='create_at',
            field=models.FloatField(default=1643886379.256574),
        ),
    ]
