# Generated by Django 4.0.1 on 2022-02-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_data_create_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name_plural': 'کاربران'},
        ),
        migrations.AlterField(
            model_name='data',
            name='create_at',
            field=models.FloatField(default=1644488166.648766),
        ),
    ]
