# Generated by Django 4.0.1 on 2022-02-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_data_options_alter_data_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='create_at',
            field=models.FloatField(default=1645709037.192767),
        ),
    ]
